apiVersion: v1
kind: Namespace
metadata:
  name: d-dev-homepage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-dev-homepage
  namespace: d-dev-homepage
  labels:
    app: homepage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
        - name: d-dev-homepage
          image: ghcr.io/dangdd2003/d-dev-homepage:main
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: '125m'
              memory: '64Mi'
            limits:
              cpu: '500m'
              memory: '256Mi'
---
apiVersion: v1
kind: Service
metadata:
  name: homepage-service
  namespace: d-dev-homepage
spec:
  selector:
    app: homepage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
  loadBalancerIP: 192.168.226.50
