name: d-dev
services:
  watchtower:
    image: containrrr/watchtower
    command:
      - '--label-enable'
      - '--interval'
      - '30'
      - '--rolling-restart'
      - '--cleanup'
      - '--remove-volumes'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
  reverse-proxy:
    image: traefik:latest
    command:
      - '--providers.docker'
      - '--providers.docker.exposedByDefault=false'
      - '--providers.file.filename=/etc/traefik/ssl-cert.yaml'
      - '--providers.file.watch=true'
      - '--entryPoints.web.address=:80'
      - '--entryPoints.web.http.redirections.entryPoint.to=websecure'
      - '--entryPoints.web.http.redirections.entryPoint.scheme=https'
      - '--entryPoints.websecure.address=:443'
      - '--entryPoints.websecure.http.tls={}'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '$PWD/.github/ssl-cert.yaml:/etc/traefik/ssl-cert.yaml:rw'
      - '$PWD/ssl-cert/:/ssl-cert'
      - '/var/run/docker.sock:/var/run/docker.sock'
  homepage:
    image: ghcr.io/dangdd2003/d-dev-homepage:main
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.homepage-router.rule=Host(`dangdd.me`) || Host(`www.dangdd.me`)'
      - 'traefik.http.routers.homepage-router.entrypoints=websecure'
      - 'traefik.http.routers.homepage-router.tls=true'
      - 'com.centurylinklabs.watchtower.enable=true'
    deploy:
      mode: replicated
      replicas: 3
