name: Docker Image Builder

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-project-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.Js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 'lts/*'

      - name: Get npm cache information
        id: cache-info
        shell: bash
        run: |
          echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
          echo "date=$(date -u "+%m/%d/%Y"" >> ${GITHUB_OUTPUT}

      - name: Cache Node.Js packages
        id: cache
        uses: actions/cache@v4.1.2
        path: ${{ steps.cache-info.outputs.dir }}
        key: ${{ runner.os }}-npm_cache-${{ steps.cache-info.outputs.date }}-${{ hashFiles('**/package-lock.json') }}
        retore-key: ${{ runner.os }}-npm_cache-

      - name: Instal dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Run linting
        run: npm run lint

      - name: Run prettier check
        run: npm run prettier:check

  build-image-and-push:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: .github/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.IMAGE_NAME }}:main
          cache-from: type=gha
          cache-to: type=gha,mode=max
